package com.zmannotes.spring.unit.test.dao;

import com.zmannotes.spring.unit.test.domain.Stock;

public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Thu May 05 21:25:27 CST 2016
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Thu May 05 21:25:27 CST 2016
     */
    int insert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Thu May 05 21:25:27 CST 2016
     */
    int insertSelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Thu May 05 21:25:27 CST 2016
     */
    Stock selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Thu May 05 21:25:27 CST 2016
     */
    int updateByPrimaryKeySelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Thu May 05 21:25:27 CST 2016
     */
    int updateByPrimaryKey(Stock record);
}